#!/bin/sh

usage() {
  echo "USAGE: ndk-which [--abi ABI] TOOL"
  echo "ABI is 'armeabi-v7a', 'arm64-v8a', 'x86', or 'x86_64'"
  echo "TOOL is 'gdb', 'objdump', 'readelf', etc."
  echo
  echo "Note that LLVM replacements for binutils tools work for all ABIs."
  exit 1
}

error() {
  echo "The tool: $1 doesn't exist"
  echo "Possible choices are: "
  count=0
  for file in $2*; do
    case "$file" in
      *"$1") echo "$file"; count=`expr $count + 1` ;;
    esac
  done
  if [ "$count" -eq 0 ]; then
    echo " None "
  fi
  exit 1
}

ABI=armeabi-v7a

while [ "$#" -gt 0 ]; do
  case "$1" in
    --abi)
      ABI="$2"
      shift 2
      case "$ABI" in
        armeabi-v7a|arm64-v8a|x86|x86_64) ;;
        *) usage ;;
      esac
      ;;
    *)
      break
      ;;
  esac
done

TOOL="$1"
shift

if [ "$#" -ne 0 ] || [ -z "$TOOL" ]; then
  usage
fi

MYNDKDIR=`dirname "$0"`/../../..

TMPDIR=/tmp/ndk-which-$$
mkdir -p "$TMPDIR/jni"
cat >"$TMPDIR/jni/Android.mk" << "END_OF_FILE"
include $(CLEAR_VARS)
END_OF_FILE

get_build_var_for_abi() {
  if [ -z "$GNUMAKE" ]; then
    GNUMAKE=make
  fi
  NDK_PROJECT_PATH="$TMPDIR" "$GNUMAKE" --no-print-dir -f "$MYNDKDIR/build/core/build-local.mk" DUMP_"$1" APP_ABI="$2"
}

LLVM_TOOLCHAIN_PREFIX=`get_build_var_for_abi LLVM_TOOLCHAIN_PREFIX "$ABI"`
TOOLCHAIN_PREFIX=`get_build_var_for_abi TOOLCHAIN_PREFIX "$ABI"`
rm -rf "$TMPDIR"

FQFN="${TOOLCHAIN_PREFIX}${TOOL}"

if [ ! -f "$FQFN" ]; then
  FQFN="${LLVM_TOOLCHAIN_PREFIX}llvm-$TOOL"
  if [ ! -f "$FQFN" ]; then
    error "$TOOL" "$LLVM_TOOLCHAIN_PREFIX"
  fi
fi

which "$FQFN"
